// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const clean = (val?: string) => val?.replace(/["']/g, "").trim() || "";

const user = clean(process.env.DB_USER);
const pass = process.env.DB_PASSWORD;
const host = clean(process.env.DB_HOST);
const port = clean(process.env.DB_PORT);
const name = clean(process.env.DB_NAME);

const databaseUrl = `mysql://${user}:${encodeURIComponent(pass || '')}@${host}:${port}/${name}`;
process.env.DATABASE_URL = databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
