// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const sanitize = (val?: string) => val?.replace(/["']/g, "").trim() || "";
const user = sanitize(process.env.DB_USER);
const pass = sanitize(process.env.DB_PASSWORD);
const host = sanitize(process.env.DB_HOST);
const port = sanitize(process.env.DB_PORT).replace(/\D/g, "");
const name = sanitize(process.env.DB_NAME);

const databaseUrl = `mysql://${user || 'root'}:${encodeURIComponent(pass)}@${host || '127.0.0.1'}:${port || '3306'}/${name || 'nextcraft'}`;
process.env.DATABASE_URL = databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
