import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/context/ToastContext";
import LoadingScreen from "@/components/Layout/LoadingScreen";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata() {
  let settings: any;
  try {
    const data: any[] = await prisma.$queryRaw`SELECT * FROM GlobalSettings LIMIT 1`;
    settings = data[0];
  } catch (e) {
    // Fallback if DB not ready
  }

  return {
    title: {
      default: settings?.siteName || "NextCraft",
      template: `%s | ${settings?.siteName || "NextCraft"}`
    },
    description: settings?.siteDescription || "Generated by NextCraft",
    keywords: settings?.siteKeywords ? settings.siteKeywords.split(",") : ["nextjs", "admin"],
    icons: {
      icon: settings?.siteFavicon || "/assets/nextcraftlogo.jpg",
      shortcut: settings?.siteFavicon || "/assets/nextcraftlogo.jpg",
    }
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050b18] text-white`}
      >
        <ToastProvider>
          <LoadingScreen />
          {children}
        </ToastProvider>
        <div className="fixed inset-0 pointer-events-none z-50 opacity-[0.03] grayscale bg-[url('https://www.transparenttextures.com/patterns/asfalt-dark.png')]" />
      </body>
    </html>
  );
}
